// puzzle's app entrypoint (side-effect): the non-gating puzzle families.
import "./sumplete/plugin"
import "./futoshiki/plugin"
import "./lightbeam/plugin"
import "./balanceScale/plugin"
import "./eclipse/plugin"
import "./constellation/plugin"
import "./starBattle/plugin"
import "./hidato/plugin"
import "./sudoku/plugin"
import "./canisters/plugin"
import "./rushHour/plugin"
import "./procession/plugin"
