// Generated by `yarn generate-seeds` — do not edit by hand.
//
// Seeds proven offline to build a graded board on their first attempt, filed by the hash of the
// options they were proven under (docs/offline-puzzle-seeds.md). Parsed from one string rather than
// written as an object literal, which is cheaper for the engine to read.
export const puzzleSeeds: Record<string, number[]> = JSON.parse("{}")
